use crate::error::{Error, Result};
use crate::model::ProtoService;
use std::fs;
use std::path::Path;

pub fn generate_service_trait(service: &ProtoService, output_dir: &Path) -> Result<()> {
    let mut content = String::new();

    content.push_str("// Generated by proto2ffi\n");
    content.push_str("// DO NOT EDIT\n\n");

    content.push_str("use prost::Message;\n");
    content.push_str("use super::ByteBuffer;\n");

    let mut message_types = std::collections::HashSet::new();
    for method in &service.methods {
        message_types.insert(&method.input_type);
        message_types.insert(&method.output_type);
    }

    if !message_types.is_empty() {
        content.push_str("use crate::{");
        let types: Vec<&str> = message_types.iter().map(|s| s.as_str()).collect();
        content.push_str(&types.join(", "));
        content.push_str("};\n");
    }

    content.push_str("\n");

    content.push_str(&format!("/// {} service trait\n", service.name));
    content.push_str("///\n");
    content.push_str("/// Implement this trait to provide the service logic.\n");
    content.push_str("/// The generated FFI exports will call these methods.\n");
    content.push_str(&format!("pub trait {} {{\n", service.camel_case_name()));

    for method in &service.methods {
        if !method.is_unary() {
            content.push_str(&format!("    // Streaming methods not yet supported: {}\n", method.name));
            continue;
        }

        content.push_str(&format!("    /// {} method\n", method.name));
        content.push_str(&format!(
            "    fn {}(&self, request: {}) -> Result<{}, Box<dyn std::error::Error>>;\n",
            method.snake_case_name(),
            method.input_type,
            method.output_type
        ));
    }

    content.push_str("}\n\n");

    content.push_str(&format!(
        "pub fn encode_message<M: Message>(msg: &M) -> Result<Vec<u8>, Box<dyn std::error::Error>> {{\n"
    ));
    content.push_str("    let mut buf = Vec::new();\n");
    content.push_str("    msg.encode(&mut buf)?;\n");
    content.push_str("    Ok(buf)\n");
    content.push_str("}\n\n");

    content.push_str(&format!(
        "pub fn decode_message<M: Message + Default>(bytes: &[u8]) -> Result<M, Box<dyn std::error::Error>> {{\n"
    ));
    content.push_str("    Ok(M::decode(bytes)?)\n");
    content.push_str("}\n");

    let file_name = format!("{}.rs", service.snake_case_name());
    let output_path = output_dir.join(file_name);
    fs::write(&output_path, content).map_err(|e| Error::Io(e))?;

    Ok(())
}
