#ifndef RUST_LIB_H
#define RUST_LIB_H

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdint.h>
#include <stdbool.h>

typedef struct ByteBuffer {
  uint8_t *ptr;
  uintptr_t len;
} ByteBuffer;

struct ByteBuffer calculator_process(const uint8_t *data_ptr, uintptr_t data_len);

void calculator_free_buffer(struct ByteBuffer buffer);

#endif  /* RUST_LIB_H */
