mod client;
mod byte_buffer_bindings;

use crate::error::{Error, Result};
use crate::model::ProtoFile;
use std::fs;
use std::path::Path;

pub fn generate(proto_files: &[ProtoFile], output_dir: &Path) -> Result<()> {
    fs::create_dir_all(output_dir).map_err(|e| Error::Io(e))?;

    byte_buffer_bindings::generate(output_dir)?;

    for proto_file in proto_files {
        for service in &proto_file.services {
            client::generate_client(service, output_dir)?;
        }
    }

    generate_barrel_file(proto_files, output_dir)?;

    Ok(())
}

fn generate_barrel_file(proto_files: &[ProtoFile], output_dir: &Path) -> Result<()> {
    let mut content = String::new();

    content.push_str("// Generated by proto2ffi\n");
    content.push_str("// DO NOT EDIT\n\n");

    content.push_str("export 'byte_buffer.dart';\n");

    for proto_file in proto_files {
        for service in &proto_file.services {
            let file_name = format!("{}_client.dart", service.snake_case_name());
            content.push_str(&format!("export '{}';\n", file_name));
        }
    }

    let output_path = output_dir.join("proto2ffi_generated.dart");
    fs::write(&output_path, content).map_err(|e| Error::Io(e))?;

    Ok(())
}
